### ISSUE TITLE
Fix book chapter links

### ISSUE THREAD

**Issue by mstreit** [jku-vds-lab/jku-vds-lab.github.io#14]
The resources side panel on the following two book chapter pages should show the publisher links pointing to the DOI.
- https://jku-vds-lab.at/edits_comments_books/2020_collaborating_domain_experts/
- https://jku-vds-lab.at/edits_comments_books/2020_case_studies_working_with_domain_experts/

Similar to here: https://jku-vds-lab.at/edits_comments_books/2014_PoV_bar_charts_box_plots/

**Comment by sSwerk** [comment]
Fixed with commits https://github.com/jku-vds-lab/jku-vds-lab.github.io/commit/b1d8eb15cb934589fad300b69a67787ac3d5bcca and https://github.com/jku-vds-lab/jku-vds-lab.github.io/commit/3d30909bfca3e02bc0958a815426d2514ede7a7c, however, the htmlproofer action fails now due to updated parameter syntax, I will have to look into it

**Comment by mstreit** [comment]
Thanks. @sSwerk are we allowed to put the Book online? Is it publicly available? Because if it's not, we need to be careful.

**Comment by sSwerk** [comment]
The publication link leads either to the embedded PDF in case the user has an active subscription (e.g. from within the JKU network) or to the book overview page: https://link.springer.com/book/10.1007/978-3-030-34444-3

**Comment by mstreit** [comment]
OK, that's good.
